from re import fullmatch


FULL = "✅ Fully Supported"
PARTIAL = "⚠ Partially Supported"
NONE = "❌ Not Supported"

actionDict = {
  "SendMessage": FULL,
  "PlaySound": FULL,
  "SendTitle": FULL,
  "SetBossBar": FULL,
  "RemoveBossBar": FULL,
  "ActionBar": FULL,
  "SendMessageSeq": FULL,
  "PlaySoundSeq": FULL,
  "SendHover": FULL,
  "StopSound": FULL,
  "SetTabListInfo": FULL,
  "GiveItems": FULL,
  "SetHotbar": FULL,
  "SetInventory": FULL,
  "SetSlotItem": FULL,
  "SetEquipment": FULL,
  "SetArmor": FULL,
  "ReplaceItems": FULL,
  "RemoveItems": FULL,
  "ClearItems": FULL,
  "SetCursorItem": FULL,
  "ClearInv": FULL,
  "SetItemCooldown": FULL,
  "SaveInv": FULL,
  "LoadInv": FULL,
  "ShowInv": FULL,
  "ExpandInv": FULL,
  "SetMenuItem": FULL,
  "SetInvName": FULL,
  "CloseInv": FULL,
  "RemoveInvRow": FULL,
  "AddInvRow": FULL,
  "OpenBlockInv": FULL,
  "Damage": FULL,
  "Heal": FULL,
  "SetHealth": FULL,
  "SetMaxHealth": FULL,
  "SetAbsorption": FULL,
  "SetFoodLevel": FULL,
  "SetSaturation": FULL,
  "GiveExp": FULL,
  "Points": FULL,
  "Level": FULL,
  "Level": FULL,
  "SetExp": FULL,
  "Points": FULL,
  "Level": FULL,
  "Level": FULL,
  "GivePotion": FULL,
  "RemovePotion": FULL,
  "ClearPotions": FULL,
  "SetSlot": FULL,
  "SetAtkSpeed": FULL,
  "SetFireTicks": FULL,
  "SetFreezeTicks": FULL,
  "SetAirTicks": FULL,
  "SetInvulTicks": FULL,
  "SetFallDistance": FULL,
  "SetSpeed": FULL,
  "SetAllowFlight": FULL,
  "SetAllowPvP": FULL,
  "SetDropsEnabled": FULL,
  "SetInventoryKept": FULL,
  "SetCollidable": FULL,
  "InstantRespawn": FULL,
  "EnableBlocks": FULL,
  "DisableBlocks": FULL,
  "DisplayHologram": FULL,
  "IsSneaking": FULL,
  "IsSprinting": FULL,
  "IsGliding": FULL,
  "IsFlying": FULL,
  "IsGrounded": FULL,
  "IsSwimming": FULL,
  "IsBlocking": FULL,
  "IsLookingAt": FULL,
  "StandingOn": FULL,
  "IsNear": FULL,
  "InWorldBorder": FULL,
  "IsHolding": FULL,
  "HasItem": FULL,
  "IsWearing": FULL,
  "NoItemCooldown": FULL,
  "HasSlotItem": FULL,
  "MenuSlotEquals": FULL,
  "CursorItem": FULL,
  "NameEquals": FULL,
  "SlotEquals": FULL,
  "SwapHands": FULL,
  "Sneak": FULL,
  "Leave": FULL,
  "Join": FULL,
  "=": FULL,
  "RandomValue": FULL,
  "PurgeVars": FULL,
  "+": FULL,
  "-": FULL,
  "x": FULL,
  "/": FULL,
  "%": FULL,
  "+=": FULL,
  "-=": FULL,
  "Exponent": FULL,
  "Root": FULL,
  "Logarithm": FULL,
  "ParseNumber": FULL,
  "AbsoluteValue": FULL,
  "ClampNumber": FULL,
  "WrapNumber": FULL,
  "Average": FULL,
  "RandomNumber": FULL,
  "Round": FULL,
  "Text": FULL,
  "ReplaceText": FULL,
  "RemoveText": FULL,
  "TrimText": FULL,
  "SplitText": FULL,
  "SetCase:": FULL,
  "TranslateColor": FULL,
  "TextLength": FULL,
  "RepeatText": FULL,
  "FormatTime": FULL,
  "CreateList": FULL,
  "AppendValue": FULL,
  "AppendList": FULL,
  "GetListValue": FULL,
  "SetListValue": FULL,
  "GetValueIndex": FULL,
  "ListLength": FULL,
  "=": FULL,
  "!=": FULL,
  ">": FULL,
  ">=": FULL,
  "<": FULL,
  "<=": FULL,
  "InRange": FULL,
  "LocIsNear": FULL,
  "Contains": FULL,
  "StartsWith": FULL,
  "EndsWith": FULL,
  "VarExists": FULL,
  "VarIsType": FULL,
  "ItemEquals": FULL,
  "ListContains": FULL,
  "ListValueEq": FULL,
  "SpawnMob": FULL,
  "SpawnItem": FULL,
  "SpawnVehicle": FULL,
  "SpawnExpOrb": FULL,
  "Explosion": FULL,
  "SpawnTNT": FULL,
  "SpawnFangs": FULL,
  "LeftClick": FULL,
  "RightClick": FULL,
  "CloudImbuePlayer": PARTIAL,
  "CloseInv": FULL,
  "StartFly": FULL,
  "PickupItem": FULL,
  "BreakBlock": FULL,
  "StartSprint": FULL,
  "ShootBow": FULL,
  "StopFly": FULL,
  "PlayerTakeDmg": FULL,
  "ProjHit": FULL,
  "KillPlayer": FULL,
  "ClickInvSlot": FULL,
  "Respawn": FULL,
  "DamageEntity": FULL,
  "PlayerHeal": FULL,
  "ClickPlayer": FULL,
  "Consume": FULL,
  "Death": FULL,
  "PlaceBlock": FULL,
  "Walk": FULL,
  "Dismount": FULL,
  "DropItem": FULL,
  "ChangeSlot": FULL,
  "ClickEntity": FULL,
  "HorseJump": FULL,
  "ShootProjectile": FULL,
  "Unsneak": FULL,
  "Fish": FULL,
  "BreakItem": FULL,
  "ClickMenuSlot": FULL,
  "Riptide": FULL,
  "KillMob": FULL,
  "EntityDmgPlayer": FULL,
  "StopSprint": FULL,
  "Jump": FULL,
  "ProjDmgPlayer": FULL,
  "PlayerDmgPlayer": FULL,
  "LaunchProj": PARTIAL,
  "Location": FULL,
  "Current Health": FULL,
  "Maximum Health": FULL,
  "Absorption Health": FULL,
  "Food Level": FULL,
  "Food Saturation": FULL,
  "Food Exhaustion": FULL,
  "Attack Damage": FULL,
  "Attack Speed": FULL,
  "Armor Points": FULL,
  "Armor Toughness": FULL,
  "Invulnerability Ticks": FULL,
  "Experience Level": FULL,
  "Experience Progress": FULL,
  "Fire Ticks": FULL,
  "Freeze Ticks": FULL,
  "Remaining Air": FULL,
  "Fall Distance": FULL,
  "Held Slot": FULL,
  "Ping": FULL
}
